### ISSUE TITLE
Clarify data integrity needs within DMARC reports

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#10]
`keyword_clarify_report` `owner:alex_brotman@comcast.com` `type_defect`   |    by seth@sethblank.com

___

The spec needs clarification to be specific about what constitutes valid data in a report.

For instance, to assure one cannot contradict oneself in a DMARC report (i.e. DKIM=fail but DMARC DKIM=pass); while this clarification should not be needed, there are many widely deployed implementations that get some of this wrong.

See: https://mailarchive.ietf.org/arch/msg/dmarc/Ii_dLXFzBNnRP361F922ty789I8/

___
_Issue migrated from trac:40 at 2022-01-24 16:16:04 +0000_

**Comment by abrotman** [comment]
Addressed in -08
