### ISSUE TITLE
DKIM correctness

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#11]
`keyword_reporting_nit` `owner:alex_brotman@comcast.com` `type_defect`   |    by seth@sethblank.com

___

The spec is ambiguous about which DKIM key needs to be reported; the aligned key used to determine the DMARC pass/fail status is the one which is needed

See: https://mailarchive.ietf.org/arch/msg/dmarc/9-V596yl2BBaUzCNaDZB1Tg1s4c/

___
_Issue migrated from trac:38 at 2022-01-24 16:15:54 +0000_

**Comment by abrotman** [comment]
I believe this is resolved several drafts ago.
