### ISSUE TITLE
XML format: version

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#12]
`type_enhancement`   |    by vesely@tana.it

___

Note added in ​http://bit.ly/dmarc-rpt-schema

It is more useful to specify the XML format version using the URI of a spec file, such as http://dmarc.org/dmarc-xml/0.2.  Therefore, it is reduntand, useless , and error prone to have a <version> element, which currently stands right at the beginning of the <feedback> element.

There are several tools that can validate XML syntax based on a specification.  To allow automated syntax verification, reports should refer to the schema version in the feedback element namespace, for example, like so:
```
<?xml version="1.0" encoding="UTF-8"?>
   <dmarc:feedback
         xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:dmarc="http://dmarc.org/dmarc-xml/0.2">
      <report_metadata>
         <org_name>example.com</org_name>
[...]
```

___
_Issue migrated from trac:33 at 2022-01-24 16:15:35 +0000_

**Comment by abrotman** [comment]
I believe this to be resolved after Ale's contributions.
