### ISSUE TITLE
Section 7.2 needs ascii art

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#3]
`owner:alex_brotman@comcast.com` `type_enhancement`   |    by mike@mtcc.com

___

it is extremely difficult to decipher the XML in the appendix for the reporting format for somebody who is not intent on implementing the draft. it would be extremely useful to have some ascii art to show the layout of the reporting structure both as an implementer and a more casual consumer of the draft. 

___
_Issue migrated from trac:102 at 2022-01-24 16:53:19 +0000_

**Comment by abrotman** [comment]
No comments on sample, closing
