### ISSUE TITLE
Codify ARC reporting in DMARC XML

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#6]
`keyword_clarify_reports` `owner:alex_brotman@comcast.com` `type_enhancement`   |    by seth@sethblank.com

___

ARC data doesn't have a clean place to live in a DMARC report. Right now, results from ARC are shimmed into a local_policy comment, but this is a text blob. ARC reporting needs a structured schema for data to come back through, and probably a new section of the DMARC report to live within.

___
_Issue migrated from trac:56 at 2022-01-24 16:17:18 +0000_

**Comment by abrotman** [comment]
See comment about extensions.  This is where ARC data should go.
