### ISSUE TITLE
Address missing report elements from deprecated drafts

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#8]
`keyword_clarify_reports` `type_defect`   |    by seth@sethblank.com

___

See: https://mailarchive.ietf.org/arch/msg/dmarc/7QmWbMMEp-TpkjGmDg0wvzhtDuQ/

___
_Issue migrated from trac:45 at 2022-01-24 16:16:23 +0000_

**Comment by abrotman** [comment]
This should be addressed with Ale's commit
