### ISSUE TITLE
Address aggregate reporting XML schema inconsistencies

### ISSUE THREAD

**Issue by ietf-svn-bot** [ietf-wg-dmarc/draft-ietf-dmarc-aggregate-reporting#9]
`keyword_clarify_reports` `owner:alex_brotman@comcast.com` `type_defect`   |    by seth@sethblank.com

___

From https://mailarchive.ietf.org/arch/msg/dmarc/kZI0bytLU9uaMmh4yQB_FTJSKX4/:

"The bottom line is that the RFC 7489 Appendix C is a mess and contradicts
itself numerous times in both schema and comments. I think it's important to
be clearer and stricter about the xml elements and their values. Too much of
this section is open to interpretation. "

For DMARCbis, the reporting XML should be consistent and sanity checked against the above.

___
_Issue migrated from trac:44 at 2022-01-24 16:16:20 +0000_

**Comment by abrotman** [comment]
Ale submitted a diff that should address this.  Closing
